#pragma config(Motor,  motor1,          MotorDriveL,   tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor6,          MotorDriveR,   tmotorVexIQ, PIDControl, encoder)
//#pragma config(Motor,  motor10,         MotorArm,      tmotorVexIQ, PIDControl, encoder)
//#pragma config(Motor,  motor11,         MotorClaw,     tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//#pragma config(Motor,  motor4,          MotorDriveS,   tmotorVexIQ, PIDControl, encoder)
#if !defined(VexIQ)
#error "This code is for the VexIQ platform"
#else


// I wonder what this does... Hint: Meow and cat hair
#define DB 10


//Motors present?
#define slide false
#define armAndClawMotor false
#define armMotor motor[motor10]
#define clawMotor motor[motor11]

void checkMacros (string &stuff)
{

#ifndef slide
#define slide false
	stuff += 'slide, ';
#endif

#ifndef armAndClawMotor
#define armAndClawMotor false
	stuff += 'armAndClawMotor, ';
#endif

#ifndef armMotor
#define armMotor motor10
	stuff += 'armMotor, ';
#endif

#ifndef clawMotor
#define clawMotor motor11
	stuff += 'clawMotor';
#endif

}
// Find if sliding to the left or sliding to the right
long checkSlide(short slideL, short slideR)
{
	if (slide) {
		if(slideL == 1 || slideL == 2) {
			return -127;
			} else if(slideR == 1 || slideR == 2) {
			return 127;
		}
	}
	return 0;

}

void printVersion(bool checkMacrosA)
{
	string& stuff = "";
	if (checkMacrosA)
		checkMacros(stuff);
	playSound(soundSiren2);
	eraseDisplay();
	displayString(1, "Leo's driver code v2.0.1 launched!");
	displayString(2, stuff);
}

void debugAllMotors()
{
	//char buf1[5];
	//char buf2[5];
	//sprintf(buf1, "%d", motor[MotorDriveL]);
	//sprintf(buf2, "%d", motor[MotorDriveR]);
	eraseDisplay();
	printVersion(false);
	displayString(2, "Motor debug:");
	displayString(3, "MotorDriveL: %d", motor[MotorDriveL]);
	displayString(4, "MotorDriveR: %d", motor[MotorDriveR]);
}

//#define   ARCADE_DRIVES

/*-----------------------------------------------------------------------------*/
/*  Control robot wheels                                                       */
/*-----------------------------------------------------------------------------*/
void
iqRunRobotDrive( )
{
	long leftDrive;
	long rightDrive;
	long slideDrive;

#if defined(ARCADE_DRIVE)
	short   forward, turn, slideL, slideR;

	// Get controller - use ChA for forward and ChB as turning
	forward = vexRT[ ChA ];
	turn    = vexRT[ ChB ];
	if (slide) {
		slideL  = vexRT[ BtnLUp ];
		slideR  = vexRT[ BtnRUp ];
	}

#if !defined(DB)
#error "Cat hair stuck in CPU and teleported into warp core! Meow!"
#endif
	// Deadband set to 10
	if( abs( forward ) < DB ) forward = 0;
	if( abs( turn )    < DB ) turn    = 0;


	// Set drive
	leftDrive  = forward + turn;
	rightDrive = forward - turn;

	// Find if sliding to the left or sliding to the right
	slideDrive = checkSlide(slideL, slideR);

#else
#if !defined(DB)
#error "Cat hair stuck in CPU and teleported into warp core! Meow!"
#endif
	short slideL, slideR;
	// Tack drive
	leftDrive  = vexRT[ ChA ];
	rightDrive = vexRT[ ChD ];
	if (slide) {
		slideL  = vexRT[ BtnLUp ];
		slideR  = vexRT[ BtnRUp ];
	}

	// Deadband set to 10
	if( abs( leftDrive )  < DB ) leftDrive  = 0;
	if( abs( rightDrive ) < DB ) rightDrive = 0;

	slideDrive = checkSlide(slideL, slideR);
#endif

	// Send to motors
	// left drive
	setMotorSpeed(MotorDriveL, leftDrive);

	// right drive
	setMotorSpeed(MotorDriveR, rightDrive);

	// slide drive
	if (slide) {
		//setMotorSpeed(MotorDriveS, slideDrive);
	}
}

/*-----------------------------------------------------------------------------*/
/*  Control the Auxiliary motors ports 10 & 11 for arm and claw                */
/*-----------------------------------------------------------------------------*/
void
iqRunRobotAux()
{
	int m10Drive;
	int m11Drive;

	// Control the auxilary motors
	m10Drive = (vexRT[ BtnLUp ] * 100) - (vexRT[ BtnLDown ] * 100);
	m11Drive = (vexRT[ BtnEUp ] * 100) - (vexRT[ BtnEDown ] * 100);

	//Motors present?
	if(armAndClawMotor) {

		// Arm motor (NOT PRESENT)
		//setMotorSpeed( armMotor, m10Drive );
		// Claw motor (NOT PRESENT)
		//setMotorSpeed( clawMotor, m11Drive );
	}
}

/*-----------------------------------------------------------------------------*/
/*  Main entry                                                                 */
/*-----------------------------------------------------------------------------*/
task main()
{

	bool meow = true;
	printVersion(meow);
	// driver control loop runs forever.
	while(1 || meow)
	{
		debugAllMotors();
		iqRunRobotDrive();
		iqRunRobotAux();
		wait1Msec(25);
	}
}

/*-----------------------------------------------------------------------------*/
#endif // #if defined(VexIQ)
