#pragma config(Sensor, port2,  gyro,           sensorVexIQ_Gyro)
#pragma config(Motor,  motor1,          lMotor,        tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor6,          rMotor,        tmotorVexIQ, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
