#pragma config(Motor,  motor1,          lMotor,        tmotorVexIQ, PIDControl, driveRight, encoder)
#pragma config(Motor,  motor4,          sMotor,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          rMotor,        tmotorVexIQ, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

